name: "å·®ä¸å¤šå…ˆç”ŸğŸ–ï¸"
description: "ä½ çœ‹å»å¹´ç¼“ç¼“æµæ·Œçš„è½»çƒŸï¼Œåˆæ€çŸ¥ä¸æ˜¯ä»Šå¹´æ»‚æ²±çš„å¤§é›¨"

avatar: https://bo88888.github.io/images/å¤´åƒ1.jpg
favicon: https://bo88888.github.io/images/favicon.ico

navigation:
  - name: é¦–é¡µ
    url: /
  - name: å…³äº
    url: /about
  - name: åˆ†ç±»
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: 
  email: 
  facebook:
  github: 
  rss: # just type anything here for a working RSS icon
  twitter: 
  youtube:

footer-text: Copyright (c) 2025

url: https://bo88888.github.io

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

